### ISSUE TITLE
Cannot find module 'amd-loader'

### ISSUE THREAD

**Issue by TravisDart** [kdelfour/cloud9-docker#9]
A couple of weeks ago, this container was working without issue. However, it isn't working now:

	$ docker rm $(docker ps -a -q)
	...
	$ docker rmi $(docker images -q)
	...
	$ docker images
	REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
	$ docker ps
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
	$ docker pull kdelfour/cloud9-docker
	...
	$ sudo docker run -it -d -p 80:80 -p 3000:3000 kdelfour/cloud9-docker
	...
	$ wget -O - localhost
	--2015-05-15 00:00:22--  http://localhost/
	Resolving localhost (localhost)... 127.0.0.1
	Connecting to localhost (localhost)|127.0.0.1|:80... connected.
	HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
	Retrying.

	--2015-05-15 00:00:23--  (try: 2)  http://localhost/
	Connecting to localhost (localhost)|127.0.0.1|:80... connected.
	HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
	Retrying.

	--2015-05-15 00:00:25--  (try: 3)  http://localhost/
	Connecting to localhost (localhost)|127.0.0.1|:80... connected.
	HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
	Retrying.

	--2015-05-15 00:00:28--  (try: 4)  http://localhost/
	Connecting to localhost (localhost)|127.0.0.1|:80... connected.
	HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
	Retrying.

	--2015-05-15 00:00:32--  (try: 5)  http://localhost/
	Connecting to localhost (localhost)|127.0.0.1|:80... connected.
	HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
	Retrying.

	^C
	$

Looking into the matter a bit more closely:

	$ docker run -it -p 80:80 -p 3000:3000 kdelfour/cloud9-docker bash
	root@1a414d7039c0:/cloud9# supervisord -n -c /etc/supervisor/supervisord.conf
	2015-05-15 14:02:25,372 CRIT Supervisor running as root (no user in config file)
	2015-05-15 14:02:25,372 WARN Included extra file "/etc/supervisor/conf.d/cloud9.conf" during parsing
	2015-05-15 14:02:25,390 INFO RPC interface 'supervisor' initialized
	2015-05-15 14:02:25,391 CRIT Server 'unix_http_server' running without any HTTP authentication checking
	2015-05-15 14:02:25,391 INFO supervisord started with pid 14
	2015-05-15 14:02:26,393 INFO spawned: 'cloud9' with pid 17
	2015-05-15 14:02:26,424 INFO exited: cloud9 (exit status 8; not expected)
	2015-05-15 14:02:27,428 INFO spawned: 'cloud9' with pid 19
	2015-05-15 14:02:27,456 INFO exited: cloud9 (exit status 8; not expected)
	2015-05-15 14:02:29,460 INFO spawned: 'cloud9' with pid 21
	2015-05-15 14:02:29,491 INFO exited: cloud9 (exit status 8; not expected)
	2015-05-15 14:02:32,499 INFO spawned: 'cloud9' with pid 23
	2015-05-15 14:02:32,528 INFO exited: cloud9 (exit status 8; not expected)
	2015-05-15 14:02:33,530 INFO gave up: cloud9 entered FATAL state, too many start retries too quickly
	^C2015-05-15 14:02:38,243 WARN received SIGINT indicating exit request
	root@1a414d7039c0:/cloud9# cat /var/log/supervisor/cloud9_errors.log

	module.js:340
		throw err;
			  ^
	Error: Cannot find module 'amd-loader'
		at Function.Module._resolveFilename (module.js:338:15)
		at Function.Module._load (module.js:280:25)
		at Module.require (module.js:364:17)
		at require (module.js:380:17)
		at Object.<anonymous> (/cloud9/server.js:4:1)
		at Module._compile (module.js:456:26)
		at Object.Module._extensions..js (module.js:474:10)
		at Module.load (module.js:356:32)
		at Function.Module._load (module.js:312:12)
		at Function.Module.runMain (module.js:497:10)

	[ ... same error repeated 3 more times ... ]

	root@1a414d7039c0:/cloud9# cat /var/log/supervisor/cloud9.log
	root@1a414d7039c0:/cloud9# 

Strangely, I found I didn't have this problem when I built the container myself using the "[Build and run with custom config directory](https://github.com/kdelfour/cloud9-docker#build-and-run-with-custom-config-directory)" instructions. I ended up going the build-it-yourself route, but the pre-built container is certainly a lot more convenient.

Note that [other people](https://github.com/c9/core/issues/1) have had this issue recently.

**Comment by kdelfour** [comment]
I have rebuild a new container image and I have deployed this new image. 
For me, it's working very well.
Can you tell me if this new image resolved your problem?

**Comment by TravisDart** [comment]
Yep, it works again. Thanks.
